# Generated by Django 4.2.11 on 2024-10-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Site", models.CharField(max_length=300)),
                ("Area", models.CharField(max_length=300)),
                ("Region", models.CharField(max_length=200)),
                ("NationalPark", models.CharField(max_length=200)),
                ("Time", models.IntegerField()),
                ("Date", models.IntegerField()),
                ("Day", models.CharField(max_length=20)),
                ("Temperature", models.FloatField()),
                ("WeatherScore", models.FloatField()),
            ],
        ),
    ]
