# Generated by Django 4.2.11 on 2024-10-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="Time",
            field=models.CharField(max_length=20),
        ),
    ]
